
POST  http://localhost:4000/api/v1/checkout/6dbb6c91-4361-4a22-9e48-d0997be84d89 HTTP/1.1
content-type: application/json

{
  "inserted": {
    "5": 1,
    "5000": 1,
    "10000": 1
  },
  "price": 14505
}

###

GET http://localhost:4000/api/v1/stock


### POST /stock

POST http://localhost:4000/api/v1/stock HTTP/1.1
content-type: application/json

{
  "data": {
    "5": 20,
    "5000": 2,
    "10000": 10
  }
}

###

PATCH http://localhost:4000/api/v1/stock/6dbb6c91-4361-4a22-9e48-d0997be84d89 HTTP/1.1
content-type: application/json

{
  "data": {
    "5": 30,
    "5000": 2,
    "10000": 10,
    "20000": 1
  }
}